# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish new AWS Lambda layer version
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and layer deployment package
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#publish-layer')"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Run script 'layer' from package
      run: npm run layer
    - name: Publish new AWS Lambda layer version
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws lambda publish-layer-version --layer-name layer-node-data-utils --zip-file fileb://dist/layer-node-data-utils.zip --compatible-runtimes nodejs14.x nodejs12.x
